<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Acara_model extends CI_Model
{
    public $table = 'acara';
    public $id = 'id_acara';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_data_acara()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_detil($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    public function delete($id) {
    return $this->db->delete('acara', array('id_acara'=>$id));
  }

     function update_acara($id_acara)
    {
       /* $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);*/
        $data = array(
        'nama_acara' => $this->input->post('nama_acara'),
        'tgl_acara' => $this->input->post('tgl_acara'),
        'alamat_acara' => $this->input->post('alamat_acara'),
        'waktu_acara' => $this->input->post('waktu_acara'),
        'nama_genre' => $this->input->post('nama_genre'),

        );

        $this->db->where('id_acara', $id_acara)
                 ->update('acara', $data);

        if ($this->db->affected_rows() > 0) 
        {
        return TRUE;
        }else{
        return FALSE;
        }
    }


    /*ublic function get_data_acara() {
        return $this->db->order_by('id_acara', 'ASC')->get('acara')->result();
    }

    public function get_detil($id) {
    return $this->db->get_where('acara',array('id_acara'=>$id));
    }*/

   public function insert($gambar) 
    {
            $data = array(
            'id_acara' => $this->input->post('id_acara'),
            'nama_acara' => $this->input->post('nama_acara'),
        'tgl_acara' => $this->input->post('tgl_acara'),
        'alamat_acara' => $this->input->post('alamat_acara'),
        'waktu_acara' => $this->input->post('waktu_acara'),
        'nama_genre' => $this->input->post('nama_genre'),
        'gambar' => $gambar['file_name']

            );
            $this->db->insert('acara', $data);
    //cek keberhasilan insert data
    if ($this->db->affected_rows() > 0) {
      return TRUE;
    } else {
      return FALSE;
    }
  }


                //konfigurasi upload file
  public function getPriceRegular($id){
    return $this->db->where('harga.jenis_tiket', 0)
                    ->where('acara.id_acara', $id)
                    ->join('acara', 'acara.id_acara = harga.id_acara', 'left')
                    ->get('harga')
                    ->result();
  }

    public function getPriceVIP($id){
    return $this->db->where('harga.jenis_tiket', 1)
                    ->where('acara.id_acara', $id)
                    ->join('acara', 'acara.id_acara = harga.id_acara', 'left')
                    ->get('harga')
                    ->result();
  }

    public function getPriceVVIP($id){
    return $this->db->where('harga.jenis_tiket', 2)
                    ->where('acara.id_acara', $id)
                    ->join('acara', 'acara.id_acara = harga.id_acara', 'left')
                    ->get('harga')
                    ->result();
  }

  
}

/* End of file Acara_model.php */
/* Location: ./application/models/Acara_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-04 03:23:56 */
/* http://harviacode.com */